### PR TITLE
Issue/removed hr holidays events pub holidays

### PR DESCRIPTION
**Pull request by BrendanCNg**
### What this PR does
Removed a hr that was between the `Holidays and events` and `Next public holiday` blocks

### Checklist
- [x] I've updated CHANGES.md with what I changed.

### CODE REVIEW

**Comment by azerella** [comment]
@BrendanCNg I think you branched off of your previous branch and didn't add the `hr` commit?

**Comment by BrendanCNg** [comment]
ah possibly, Do you want me to make a new PR?

**Comment by BrendanCNg** [comment]
I think i have resolved this.

**Review by azerella — CHANGES_REQUESTED** [review]
@BrendanCNg Still doesn't seem to be resolved? It might be faster to create a new branch with your specific change, if not try `git reset HEAD~1` to undo your latest commits

**Pull request closed without merging**
